export const emojiCategories = [
  {
    id: 'smileys',
    name: '😊 笑脸与情感',
    emojis: [
      { emoji: '😀', name: '笑脸', keywords: ['开心', '微笑', '高兴'], codes: [':grinning:', ':-D'], aliases: ['露齿笑', '开心脸'] },
      { emoji: '😃', name: '大笑', keywords: ['开心', '笑', '快乐'], codes: [':smiley:', '=)'], aliases: ['开心大笑', '笑脸'] },
      { emoji: '😄', name: '开心笑', keywords: ['开心', '笑', '高兴'], codes: [':smile:', ':-)'], aliases: ['开心脸', '微笑'] },
      { emoji: '😁', name: '嘻嘻', keywords: ['笑', '开心', '快乐'], codes: [':grin:', '^_^'], aliases: ['咧嘴笑', '嘻嘻笑'] },
      { emoji: '😆', name: '斜眼笑', keywords: ['笑', '开心', '高兴'], codes: [':laughing:', 'XD'], aliases: ['眯眼笑', '斜眼看'] },
      { emoji: '😅', name: '苦笑', keywords: ['尴尬', '汗', '紧张'], codes: [':sweat_smile:', ':\')'], aliases: ['汗笑', '尴尬笑'] },
      { emoji: '🤣', name: '笑到打滚', keywords: ['笑', '开心', '搞笑'], codes: [':rofl:', ';D'], aliases: ['滚地笑', '笑死'] },
      { emoji: '😂', name: '笑哭', keywords: ['笑', '哭', '开心'], codes: [':joy:', ':\'D'], aliases: ['喜极而泣', '笑哭了'] },
      { emoji: '🙂', name: '微笑', keywords: ['微笑', '开心', '友好'], codes: [':slight_smile:', ':)'], aliases: ['轻微笑', '温和笑'] },
      { emoji: '🙃', name: '倒脸', keywords: ['调皮', '搞怪', '有趣'], codes: [':upside_down:', '(:'], aliases: ['倒过来', '颠倒脸'] },
      { emoji: '😉', name: '眨眼', keywords: ['眨眼', '调皮', '暗示'], codes: [':wink:', ';-)'], aliases: ['使眼色', '眨眼笑'] },
      { emoji: '😊', name: '害羞笑', keywords: ['害羞', '开心', '微笑'], codes: [':blush:', '^_^'], aliases: ['脸红笑', '腼腆笑'] },
      { emoji: '😇', name: '天使', keywords: ['天使', '纯洁', '无辜'], codes: [':innocent:', 'O:)'], aliases: ['光环', '圣人笑'] },
      { emoji: '🥰', name: '喜欢', keywords: ['爱', '喜欢', '心动'], codes: [':heart_eyes:', '<3'], aliases: ['爱心眼', '喜爱'] },
      { emoji: '😍', name: '花痴', keywords: ['爱', '喜欢', '心动'], codes: [':heart_eyes:', ':*'], aliases: ['爱心眼', '迷恋'] },
      { emoji: '🤩', name: '星星眼', keywords: ['崇拜', '惊艳', '喜欢'], codes: [':star_struck:', ':*'], aliases: ['惊艳', '两眼放光'] },
      { emoji: '😘', name: '飞吻', keywords: ['亲吻', '爱', '喜欢'], codes: [':kissing_heart:', ':-*'], aliases: ['飞吻', '亲亲'] },
      { emoji: '😗', name: '亲亲', keywords: ['亲吻', '爱'], codes: [':kissing:', ':*'], aliases: ['亲吻', '嘴嘴'] },
      { emoji: '😙', name: '笑亲亲', keywords: ['亲吻', '爱', '开心'], codes: [':kissing_smiling_eyes:', ';*'], aliases: ['微笑亲', '笑吻'] },
      { emoji: '😚', name: '害羞亲亲', keywords: ['亲吻', '爱', '害羞'], codes: [':kissing_closed_eyes:', ':*'], aliases: ['闭眼睛亲', '腼腆吻'] },
      { emoji: '😋', name: '馋嘴', keywords: ['吃', '美味', '馋'], codes: [':yum:', ':P'], aliases: ['舔嘴唇', '好吃'] },
      { emoji: '😛', name: '吐舌', keywords: ['调皮', '搞怪', '吐舌'], codes: [':stuck_out_tongue:', ':P'], aliases: ['伸舌头', '俏皮'] },
      { emoji: '😜', name: '眨眼吐舌', keywords: ['调皮', '搞怪', '吐舌'], codes: [':stuck_out_tongue_winking_eye:', ';P'], aliases: ['眨眼伸舌', '搞怪'] },
      { emoji: '🤪', name: '搞怪', keywords: ['疯狂', '搞怪', '有趣'], codes: [':zany_face:', 'xP'], aliases: ['滑稽', '古怪'] },
      { emoji: '😝', name: '眯眼吐舌', keywords: ['调皮', '搞怪', '开心'], codes: [':stuck_out_tongue_closed_eyes:', 'xP'], aliases: ['眯眼伸舌', '俏皮笑'] },
      { emoji: '🤑', name: '发财', keywords: ['钱', '发财', '富有'], codes: [':money_mouth:', '$_$'], aliases: ['钱眼', '发财了'] },
      { emoji: '🤗', name: '拥抱', keywords: ['拥抱', '友好', '欢迎'], codes: [':hugs:', '()'], aliases: ['抱抱', '张开双臂'] },
      { emoji: '🤭', name: '捂嘴笑', keywords: ['害羞', '笑', '尴尬'], codes: [':hand_over_mouth:', ':)'], aliases: ['偷笑', '掩嘴'] },
      { emoji: '🤫', name: '嘘', keywords: ['安静', '保密', '小声'], codes: [':shushing_face:', 'shh'], aliases: ['小声点', '别说话'] },
      { emoji: '🤔', name: '思考', keywords: ['思考', '想', '疑问'], codes: [':thinking:', '?'], aliases: ['想想', '琢磨'] },
      { emoji: '🤐', name: '闭嘴', keywords: ['闭嘴', '不说', '保密'], codes: [':zipper_mouth:', ':-X'], aliases: ['拉链嘴', '保密'] },
      { emoji: '🤨', name: '挑眉', keywords: ['怀疑', '疑问', '打量'], codes: [':raised_eyebrow:', ':/'], aliases: ['怀疑脸', '挑眉'] },
      { emoji: '😐', name: '面无表情', keywords: ['平淡', '无表情', '冷静'], codes: [':neutral_face:', ':-|'], aliases: ['无表情', '淡定'] },
      { emoji: '😑', name: '无语', keywords: ['无语', '无奈', '平静'], codes: [':expressionless:', '-_-'], aliases: ['没表情', '冷淡'] },
      { emoji: '😶', name: '沉默', keywords: ['沉默', '不说', '安静'], codes: [':no_mouth:', ':-x'], aliases: ['没嘴巴', '安静'] },
      { emoji: '😏', name: '得意', keywords: ['得意', '自信', '骄傲'], codes: [':smirk:', ';]'], aliases: ['坏笑', '得意笑'] },
      { emoji: '😒', name: '不爽', keywords: ['不爽', '不满', '生气'], codes: [':unamused:', ':/'], aliases: ['不高兴', '没兴趣'] },
      { emoji: '🙄', name: '翻白眼', keywords: ['无语', '不耐烦', '鄙视'], codes: [':roll_eyes:', '=_='], aliases: ['转眼睛', '鄙视'] },
      { emoji: '😬', name: '咬牙', keywords: ['紧张', '尴尬', '害怕'], codes: [':grimacing:', ':-S'], aliases: ['龇牙', '紧张'] },
      { emoji: '🤥', name: '撒谎', keywords: ['撒谎', '不诚实', '鼻子长'], codes: [':lying_face:', ':)'], aliases: ['说谎', '匹诺曹'] },
      { emoji: '😌', name: '松口气', keywords: ['放松', '安心', '释然'], codes: [':relieved:', ':)'], aliases: ['放心', '松了口气'] },
      { emoji: '😔', name: '郁闷', keywords: ['难过', '郁闷', '失落'], codes: [':pensive:', ':('], aliases: ['沉思', '忧郁'] },
      { emoji: '😪', name: '困', keywords: ['困', '累', '想睡'], codes: [':sleepy:', ':-O'], aliases: ['打哈欠', '想睡觉'] },
      { emoji: '🤤', name: '流口水', keywords: ['馋', '美味', '想吃'], codes: [':drooling_face:', ':P'], aliases: ['流口水', '垂涎'] },
      { emoji: '😴', name: '睡觉', keywords: ['睡觉', '困', '休息'], codes: [':sleeping:', 'zzz'], aliases: ['睡着', '打呼'] },
      { emoji: '😷', name: '口罩', keywords: ['生病', '口罩', '健康'], codes: [':mask:', ':-x'], aliases: ['戴口罩', '防疫'] },
      { emoji: '🤒', name: '发烧', keywords: ['生病', '发烧', '不舒服'], codes: [':thermometer_face:', '>:('], aliases: ['体温计', '感冒'] },
      { emoji: '🤕', name: '受伤', keywords: ['受伤', '疼痛', '医院'], codes: [':head_bandage:', 'X('], aliases: ['头受伤', '绷带'] },
      { emoji: '🤢', name: '恶心', keywords: ['恶心', '想吐', '不舒服'], codes: [':nauseated_face:', ':-X'], aliases: ['反胃', '想吐'] },
      { emoji: '🤮', name: '呕吐', keywords: ['呕吐', '恶心', '生病'], codes: [':vomiting:', ':-X'], aliases: ['吐了', '反胃'] },
      { emoji: '🤧', name: '打喷嚏', keywords: ['感冒', '打喷嚏', '生病'], codes: [':sneezing_face', ':-X'], aliases: ['感冒', '流鼻涕'] },
      { emoji: '🥵', name: '热', keywords: ['热', '出汗', '夏天'], codes: [':hot_face:', '>_<'], aliases: ['好热', '热死了'] },
      { emoji: '🥶', name: '冷', keywords: ['冷', '冬天', '发抖'], codes: [':cold_face:', 'o_o'], aliases: ['好冷', '冻僵'] },
      { emoji: '🥴', name: '醉', keywords: ['醉', '头晕', '迷糊'], codes: [':woozy_face', '@_@'], aliases: ['晕乎乎', '喝醉'] },
      { emoji: '😵', name: '晕', keywords: ['晕', '头晕', '昏倒'], codes: [':dizzy_face:', 'x_x'], aliases: ['眩晕', '昏倒'] },
      { emoji: '🤯', name: '爆炸头', keywords: ['震惊', '惊讶', '爆炸'], codes: [':exploding_head:', 'O_O'], aliases: ['震惊', '脑子炸了'] },
      { emoji: '🤠', name: '牛仔', keywords: ['牛仔', '酷', '帽子'], codes: [':cowboy:', ':D'], aliases: ['牛仔帽', '西部'] },
      { emoji: '🥳', name: '派对', keywords: ['庆祝', '派对', '开心'], codes: [':partying_face:', ':D'], aliases: ['庆祝', '生日趴'] },
      { emoji: '🥸', name: '伪装', keywords: ['伪装', '眼镜', '胡子'], codes: [':disguised_face:', ':)'], aliases: ['变装', '伪装者'] },
      { emoji: '😎', name: '墨镜', keywords: ['酷', '墨镜', '帅气'], codes: [':sunglasses:', 'B)'], aliases: ['戴墨镜', '酷帅'] },
      { emoji: '🤓', name: '书呆子', keywords: [' nerd', '眼镜', '聪明'], codes: [':nerd:', '8)'], aliases: ['书呆子', '学霸'] },
      { emoji: '🧐', name: '单片眼镜', keywords: ['打量', '怀疑', ' monocle'], codes: [':monocle:', '8)'], aliases: ['单片镜', '侦探'] },
      { emoji: '😕', name: '困惑', keywords: ['困惑', '疑惑', '不确定'], codes: [':confused:', ':/'], aliases: ['疑惑', '搞不懂'] },
      { emoji: '😟', name: '担心', keywords: ['担心', '焦虑', '害怕'], codes: [':worried:', ':('], aliases: ['担忧', '焦虑'] },
      { emoji: '🙁', name: '难过', keywords: ['难过', '不开心', '失望'], codes: [':slightly_frowning:', ':('], aliases: ['轻微难过', '不开心'] },
      { emoji: '☹️', name: '皱眉', keywords: ['难过', '生气', '不满'], codes: [':frowning:', ':('], aliases: ['皱眉头', '不高兴'] },
      { emoji: '😮', name: '惊讶', keywords: ['惊讶', '吃惊', '意外'], codes: [':open_mouth:', ':-O'], aliases: ['张嘴惊讶', '吃惊'] },
      { emoji: '😯', name: '沉默惊讶', keywords: ['惊讶', '吃惊', '意外'], codes: [':hushed:', ':-o'], aliases: ['安静惊讶', '小声'] },
      { emoji: '😲', name: '震惊', keywords: ['震惊', '惊讶', '意外'], codes: [':astonished:', 'O_O'], aliases: ['惊呆', '震惊'] },
      { emoji: '😳', name: '脸红', keywords: ['害羞', '尴尬', '脸红'], codes: [':flushed:', '>:o'], aliases: ['害羞脸红', '尴尬'] },
      { emoji: '🥺', name: '求你', keywords: ['可怜', '请求', '可爱'], codes: [':pleading_face:', ':-('], aliases: ['求求你', '可怜巴巴'] },
      { emoji: '😦', name: '皱眉张嘴', keywords: ['惊讶', '担心', '害怕'], codes: [':frowning_mouth_with_open_mouth:', ':-O'], aliases: ['皱眉惊讶', '担心'] },
      { emoji: '😧', name: '痛苦', keywords: ['痛苦', '难过', '担心'], codes: [':anguished:', 'D:'], aliases: ['痛苦脸', '难受'] },
      { emoji: '😨', name: '害怕', keywords: ['害怕', '恐惧', '担心'], codes: [':fearful:', 'D:' ], aliases: ['恐惧', '吓人'] },
      { emoji: '😰', name: '焦虑出汗', keywords: ['焦虑', '紧张', '害怕'], codes: [':cold_sweat:', ':-S'], aliases: ['紧张流汗', '焦虑'] },
      { emoji: '😥', name: '失望', keywords: ['失望', '难过', '放松'], codes: [':disappointed_relieved:', ':\'('], aliases: ['失望但释然', '松口气'] },
      { emoji: '😢', name: '哭', keywords: ['哭', '难过', '流泪'], codes: [':cry:', ':\'('], aliases: ['哭泣', '流泪'] },
      { emoji: '😭', name: '大哭', keywords: ['哭', '难过', '伤心'], codes: [':sob:', 'T_T'], aliases: ['痛哭', '流泪不止'] },
      { emoji: '😱', name: '恐惧', keywords: ['害怕', '恐惧', '尖叫'], codes: [':scream:', 'O_O'], aliases: ['尖叫', '吓死了'] },
      { emoji: '😖', name: '困扰', keywords: ['困扰', '烦恼', '痛苦'], codes: [':confounded', '>_<'], aliases: ['烦躁', '纠结'] },
      { emoji: '😣', name: '忍耐', keywords: ['忍耐', '痛苦', '努力'], codes: [':persevere:', '>_<'], aliases: ['坚持', '忍耐'] },
      { emoji: '😞', name: '失望', keywords: ['失望', '难过', '失落'], codes: [':disappointed:', ':('], aliases: ['失意', '灰心'] },
      { emoji: '😓', name: '汗', keywords: ['紧张', '尴尬', '努力'], codes: [':sweat:', ':-S'], aliases: ['流汗', '紧张'] },
      { emoji: '😩', name: '疲惫', keywords: ['疲惫', '累', '压力'], codes: [':weary:', '>_<'], aliases: ['疲倦', '累瘫'] },
      { emoji: '😫', name: '累坏', keywords: ['累', '疲惫', '精疲力尽'], codes: [':tired_face:', '>_<'], aliases: ['累坏了', '精疲力竭'] },
      { emoji: '🥱', name: '打哈欠', keywords: ['困', '累', '无聊'], codes: [':yawning_face:', 'O_o'], aliases: ['困了', '打哈欠'] },
      { emoji: '😤', name: '生气', keywords: ['生气', '愤怒', '不满'], codes: [':triumph:', '>:('], aliases: ['气哼哼', '愤怒'] },
      { emoji: '😡', name: '愤怒', keywords: ['生气', '愤怒', '火大'], codes: [':rage:', '>:('], aliases: ['暴怒', '火大'] },
      { emoji: '😠', name: '不满', keywords: ['生气', '不满', '愤怒'], codes: [':angry:', '>:('], aliases: ['生气', '不高兴'] },
      { emoji: '🤬', name: '骂人', keywords: ['生气', '愤怒', '骂人'], codes: [':cursing:', ':@'], aliases: ['脏话', '怒骂'] },
      { emoji: '😈', name: '恶魔笑', keywords: ['恶魔', '调皮', '邪恶'], codes: [':smiling_imp:', '>:)'], aliases: ['小恶魔', '调皮鬼'] },
      { emoji: '👿', name: '恶魔', keywords: ['恶魔', '生气', '邪恶'], codes: [':imp:', '>:('], aliases: ['恶魔', '生气鬼'] },
      { emoji: '💀', name: '骷髅', keywords: ['骷髅', '死亡', '恐怖'], codes: [':skull:', 'x_x'], aliases: ['头骨', '死亡'] },
      { emoji: '☠️', name: '危险', keywords: ['危险', '死亡', '骷髅'], codes: [':skull_and_crossbones:', 'x_x'], aliases: ['骷髅头', '危险'] },
      { emoji: '💩', name: '便便', keywords: ['便便', '屎', '搞笑'], codes: [':poop:', '~_~'], aliases: ['大便', '屎粑粑'] },
      { emoji: '🤡', name: '小丑', keywords: ['小丑', '搞笑', '马戏团'] },
      { emoji: '👹', name: '恶鬼', keywords: ['鬼', '怪物', '恐怖'] },
      { emoji: '👺', name: '天狗', keywords: ['鬼', '怪物', '日本'] },
      { emoji: '👻', name: '幽灵', keywords: ['幽灵', '鬼', '万圣节'] },
      { emoji: '👽', name: '外星人', keywords: ['外星人', 'UFO', '太空'] },
      { emoji: '👾', name: '外星怪物', keywords: ['外星人', '怪物', '游戏'] },
      { emoji: '🤖', name: '机器人', keywords: ['机器人', '科技', '未来'] },
      { emoji: '😺', name: '猫笑', keywords: ['猫', '笑', '开心'] },
      { emoji: '😸', name: '猫开心', keywords: ['猫', '开心', '笑'] },
      { emoji: '😹', name: '猫笑哭', keywords: ['猫', '笑', '哭'] },
      { emoji: '😻', name: '猫花痴', keywords: ['猫', '爱', '喜欢'] },
      { emoji: '😼', name: '猫得意', keywords: ['猫', '得意', '微笑'] },
      { emoji: '😽', name: '猫亲亲', keywords: ['猫', '亲吻', '爱'] },
      { emoji: '🙀', name: '猫惊讶', keywords: ['猫', '惊讶', '意外'] },
      { emoji: '😿', name: '猫哭', keywords: ['猫', '哭', '难过'] },
      { emoji: '😾', name: '猫生气', keywords: ['猫', '生气', '不满'] },
      { emoji: '💋', name: '唇印', keywords: ['亲吻', '爱', '口红'] },
      { emoji: '💌', name: '情书', keywords: ['信', '爱', '浪漫'] },
      { emoji: '💘', name: '丘比特', keywords: ['爱', '心动', '浪漫'] },
      { emoji: '💝', name: '爱心礼物', keywords: ['爱', '礼物', '心'] },
      { emoji: '💖', name: '闪亮爱心', keywords: ['爱', '闪亮', '心'] },
      { emoji: '💗', name: '成长爱心', keywords: ['爱', '成长', '心'] },
      { emoji: '💓', name: '跳动爱心', keywords: ['爱', '心跳', '心动'] },
      { emoji: '💞', name: '旋转爱心', keywords: ['爱', '旋转', '心'] },
      { emoji: '💕', name: '两颗心', keywords: ['爱', '两颗心', '浪漫'] },
      { emoji: '💟', name: '爱心装饰', keywords: ['爱', '装饰', '心'] },
      { emoji: '❣️', name: '感叹爱心', keywords: ['爱', '感叹', '心'] },
      { emoji: '💔', name: '心碎', keywords: ['心碎', '难过', '分手'] },
      { emoji: '❤️', name: '红心', keywords: ['爱', '心', '红心'] },
      { emoji: '🧡', name: '橙心', keywords: ['爱', '心', '橙色'] },
      { emoji: '💛', name: '黄心', keywords: ['爱', '心', '黄色'] },
      { emoji: '💚', name: '绿心', keywords: ['爱', '心', '绿色'] },
      { emoji: '💙', name: '蓝心', keywords: ['爱', '心', '蓝色'] },
      { emoji: '💜', name: '紫心', keywords: ['爱', '心', '紫色'] },
      { emoji: '🤎', name: '棕心', keywords: ['爱', '心', '棕色'] },
      { emoji: '🖤', name: '黑心', keywords: ['爱', '心', '黑色'] },
      { emoji: '🤍', name: '白心', keywords: ['爱', '心', '白色'] },
      { emoji: '💯', name: '满分', keywords: ['满分', '完美', '100分'] },
      { emoji: '💢', name: '怒', keywords: ['生气', '愤怒', '火大'] },
      { emoji: '💥', name: '爆炸', keywords: ['爆炸', '砰', '冲击'] },
      { emoji: '💫', name: '头晕', keywords: ['头晕', '眩晕', '星星'] },
      { emoji: '💦', name: '汗滴', keywords: ['汗', '水', '运动'] },
      { emoji: '💨', name: '逃跑', keywords: ['跑', '风', '快'] },
      { emoji: '🕳️', name: '洞', keywords: ['洞', '坑', '空'] },
      { emoji: '💬', name: '对话', keywords: ['说话', '聊天', '对话'] },
      { emoji: '👁️‍🗨️', name: '思想泡泡', keywords: ['想', '思考', '想法'] },
      { emoji: '🗨️', name: '说话', keywords: ['说话', '聊天', '对话'] },
      { emoji: '🗯️', name: '愤怒对话', keywords: ['生气', '说话', '对话'] },
      { emoji: '💭', name: '思想', keywords: ['想', '思考', '想法'] },
      { emoji: '💤', name: '睡觉', keywords: ['睡觉', '困', 'zzz'] }
    ]
  },
  {
    id: 'people',
    name: '👤 人物与身体',
    emojis: [
      { emoji: '👋', name: '挥手', keywords: ['再见', '你好', '打招呼'] },
      { emoji: '🤚', name: '抬手', keywords: ['手', '举', '停止'] },
      { emoji: '🖐️', name: '手掌', keywords: ['手', '掌', '停止'] },
      { emoji: '✋', name: '举手', keywords: ['手', '停止', '举手'] },
      { emoji: '🖖', name: '瓦肯举手礼', keywords: ['手', '星际迷航', '问候'] },
      { emoji: '👌', name: 'OK', keywords: ['好', 'ok', '没问题'] },
      { emoji: '🤌', name: '捏手指', keywords: ['手', '捏', '意大利'] },
      { emoji: '🤏', name: '捏', keywords: ['手', '捏', '小'] },
      { emoji: '✌️', name: '剪刀手', keywords: ['胜利', '和平', '剪刀手'] },
      { emoji: '🤞', name: '祈祷手', keywords: ['好运', '祈祷', '希望'] },
      { emoji: '🤟', name: '爱你', keywords: ['爱', '摇滚', '手势'] },
      { emoji: '🤘', name: '摇滚', keywords: ['摇滚', '金属', '音乐'] },
      { emoji: '🤙', name: '打电话', keywords: ['电话', '联系', 'call me'] },
      { emoji: '👈', name: '左指', keywords: ['指', '左边', '方向'] },
      { emoji: '👉', name: '右指', keywords: ['指', '右边', '方向'] },
      { emoji: '👆', name: '上指', keywords: ['指', '上边', '方向'] },
      { emoji: '🖕', name: '竖中指', keywords: ['中指', 'fuck', '侮辱'] },
      { emoji: '👇', name: '下指', keywords: ['指', '下边', '方向'] },
      { emoji: '☝️', name: '注意', keywords: ['指', '注意', '上边'] },
      { emoji: '👍', name: '点赞', keywords: ['好', '赞', '棒'] },
      { emoji: '👎', name: '踩', keywords: ['不好', '差', '烂'] },
      { emoji: '✊', name: '拳头', keywords: ['拳头', '力量', '加油'] },
      { emoji: '👊', name: '出拳', keywords: ['拳头', '打', '力量'] },
      { emoji: '🤛', name: '左拳', keywords: ['拳头', '左边', '碰拳'] },
      { emoji: '🤜', name: '右拳', keywords: ['拳头', '右边', '碰拳'] },
      { emoji: '👏', name: '鼓掌', keywords: ['拍手', '鼓掌', '很棒'] },
      { emoji: '🙌', name: '举手庆祝', keywords: ['庆祝', '开心', '欢呼'] },
      { emoji: '👐', name: '张开双手', keywords: ['拥抱', '开放', '双手'] },
      { emoji: '🤲', name: '手心向上', keywords: ['祈祷', '请求', '给予'] },
      { emoji: '🤝', name: '握手', keywords: ['握手', '合作', '友好'] },
      { emoji: '🙏', name: '祈祷', keywords: ['祈祷', '感谢', '请求'] },
      { emoji: '✍️', name: '写字', keywords: ['写', '笔', '记录'] },
      { emoji: '💅', name: '美甲', keywords: ['指甲', '美甲', '漂亮'] },
      { emoji: '🤳', name: '自拍', keywords: ['自拍', '手机', '拍照'] },
      { emoji: '💪', name: '肌肉', keywords: ['强壮', '肌肉', '力量'] },
      { emoji: '🦾', name: '机械臂', keywords: ['机器人', '力量', '机械'] },
      { emoji: '🦿', name: '机械腿', keywords: ['机器人', '腿', '机械'] },
      { emoji: '🦵', name: '腿', keywords: ['腿', '脚', '踢'] },
      { emoji: '🦶', name: '脚', keywords: ['脚', '足', '踩'] },
      { emoji: '👂', name: '耳朵', keywords: ['耳朵', '听', '声音'] },
      { emoji: '🦻', name: '听障', keywords: ['耳朵', '听障', '辅助'] },
      { emoji: '👃', name: '鼻子', keywords: ['鼻子', '闻', '嗅'] },
      { emoji: '🧠', name: '大脑', keywords: ['大脑', '思考', '聪明'] },
      { emoji: '🦷', name: '牙齿', keywords: ['牙齿', '牙', '牙医'] },
      { emoji: '🦴', name: '骨头', keywords: ['骨头', '骨骼', '骨折'] },
      { emoji: '👀', name: '眼睛', keywords: ['眼睛', '看', '注视'] },
      { emoji: '👁️', name: '单眼', keywords: ['眼睛', '看', '单眼'] },
      { emoji: '👅', name: '舌头', keywords: ['舌头', '舔', '馋'] },
      { emoji: '👄', name: '嘴', keywords: ['嘴', '口', '说话'] },
      { emoji: '👶', name: '宝宝', keywords: ['婴儿', '宝宝', '小孩'] },
      { emoji: '👧', name: '小女孩', keywords: ['女孩', '小孩', '女儿'] },
      { emoji: '🧒', name: '小孩', keywords: ['小孩', '孩子', '儿童'] },
      { emoji: '👦', name: '小男孩', keywords: ['男孩', '小孩', '儿子'] },
      { emoji: '👩', name: '女人', keywords: ['女人', '女性', '成人'] },
      { emoji: '🧑', name: '成人', keywords: ['成人', '人', '中性'] },
      { emoji: '👨', name: '男人', keywords: ['男人', '男性', '成人'] },
      { emoji: '👵', name: '老奶奶', keywords: ['老人', '奶奶', '女性'] },
      { emoji: '🧓', name: '老人', keywords: ['老人', '长辈', '成人'] },
      { emoji: '👴', name: '老爷爷', keywords: ['老人', '爷爷', '男性'] },
      { emoji: '👲', name: '戴瓜皮帽', keywords: ['帽子', '中国', '传统'] },
      { emoji: '👳', name: '戴头巾', keywords: ['头巾', '穆斯林', '传统'] },
      { emoji: '👷', name: '建筑工人', keywords: ['工人', '建筑', '安全帽'] },
      { emoji: '👮', name: '警察', keywords: ['警察', '保安', '安全'] },
      { emoji: '💂', name: '卫兵', keywords: ['卫兵', '守卫', '士兵'] },
      { emoji: '🕵️', name: '侦探', keywords: ['侦探', '间谍', '调查'] },
      { emoji: '👩‍⚕️', name: '女医生', keywords: ['医生', '护士', '医院'] },
      { emoji: '👨‍⚕️', name: '男医生', keywords: ['医生', '护士', '医院'] },
      { emoji: '👩‍🎓', name: '女学生', keywords: ['学生', '毕业', '学校'] },
      { emoji: '👨‍🎓', name: '男学生', keywords: ['学生', '毕业', '学校'] },
      { emoji: '👩‍🏫', name: '女老师', keywords: ['老师', '教师', '学校'] },
      { emoji: '👨‍🏫', name: '男老师', keywords: ['老师', '教师', '学校'] },
      { emoji: '👩‍⚖️', name: '女法官', keywords: ['法官', '律师', '法院'] },
      { emoji: '👨‍⚖️', name: '男法官', keywords: ['法官', '律师', '法院'] },
      { emoji: '👩‍🌾', name: '女农民', keywords: ['农民', '农业', '农场'] },
      { emoji: '👨‍🌾', name: '男农民', keywords: ['农民', '农业', '农场'] },
      { emoji: '👩‍🍳', name: '女厨师', keywords: ['厨师', '烹饪', '厨房'] },
      { emoji: '👨‍🍳', name: '男厨师', keywords: ['厨师', '烹饪', '厨房'] },
      { emoji: '👩‍🔧', name: '女技工', keywords: ['技工', '修理', '工具'] },
      { emoji: '👨‍🔧', name: '男技工', keywords: ['技工', '修理', '工具'] },
      { emoji: '👩‍🏭', name: '女工人', keywords: ['工人', '工厂', '工业'] },
      { emoji: '👨‍🏭', name: '男工人', keywords: ['工人', '工厂', '工业'] },
      { emoji: '👩‍💼', name: '女白领', keywords: ['白领', '办公', '商务'] },
      { emoji: '👨‍💼', name: '男白领', keywords: ['白领', '办公', '商务'] },
      { emoji: '👩‍🔬', name: '女科学家', keywords: ['科学家', '实验', '研究'] },
      { emoji: '👨‍🔬', name: '男科学家', keywords: ['科学家', '实验', '研究'] },
      { emoji: '👩‍💻', name: '女程序员', keywords: ['程序员', '电脑', '技术'] },
      { emoji: '👨‍💻', name: '男程序员', keywords: ['程序员', '电脑', '技术'] },
      { emoji: '👩‍🎤', name: '女歌手', keywords: ['歌手', '音乐', '明星'] },
      { emoji: '👨‍🎤', name: '男歌手', keywords: ['歌手', '音乐', '明星'] },
      { emoji: '👩‍🎨', name: '女艺术家', keywords: ['艺术家', '画家', '创意'] },
      { emoji: '👨‍🎨', name: '男艺术家', keywords: ['艺术家', '画家', '创意'] },
      { emoji: '👩‍✈️', name: '女飞行员', keywords: ['飞行员', '飞机', '驾驶'] },
      { emoji: '👨‍✈️', name: '男飞行员', keywords: ['飞行员', '飞机', '驾驶'] },
      { emoji: '👩‍🚀', name: '女宇航员', keywords: ['宇航员', '太空', '火箭'] },
      { emoji: '👨‍🚀', name: '男宇航员', keywords: ['宇航员', '太空', '火箭'] },
      { emoji: '👩‍🚒', name: '女消防员', keywords: ['消防员', '灭火', '救援'] },
      { emoji: '👨‍🚒', name: '男消防员', keywords: ['消防员', '灭火', '救援'] },
      { emoji: '👯', name: '兔女郎', keywords: ['跳舞', '派对', '兔子'] },
      { emoji: '🧖', name: '蒸桑拿', keywords: ['桑拿', '放松', '温泉'] },
      { emoji: '🧗', name: '攀岩', keywords: ['攀岩', '爬山', '运动'] },
      { emoji: '🤺', name: '击剑', keywords: ['击剑', '运动', '剑'] },
      { emoji: '🏇', name: '骑马', keywords: ['骑马', '赛马', '运动'] },
      { emoji: '⛷️', name: '滑雪', keywords: ['滑雪', '冬天', '运动'] },
      { emoji: '🏂', name: '单板滑雪', keywords: ['滑雪', '单板', '冬天'] },
      { emoji: '🏌️', name: '打高尔夫', keywords: ['高尔夫', '运动', '球'] },
      { emoji: '🏄', name: '冲浪', keywords: ['冲浪', '水上', '运动'] },
      { emoji: '🚣', name: '划船', keywords: ['划船', '水上', '运动'] },
      { emoji: '🏊', name: '游泳', keywords: ['游泳', '水上', '运动'] },
      { emoji: '⛹️', name: '拍球', keywords: ['篮球', '运动', '球'] },
      { emoji: '🏋️', name: '举重', keywords: ['举重', '健身', '运动'] },
      { emoji: '🚴', name: '骑自行车', keywords: ['自行车', '骑行', '运动'] },
      { emoji: '🚵', name: '骑山地车', keywords: ['自行车', '山地', '运动'] },
      { emoji: '🤸', name: '侧手翻', keywords: ['体操', '翻跟斗', '运动'] },
      { emoji: '🤽', name: '水球', keywords: ['水球', '水上', '运动'] },
      { emoji: '🤾', name: '手球', keywords: ['手球', '运动', '球'] },
      { emoji: '🤹', name: '杂耍', keywords: ['杂耍', '马戏团', '技巧'] },
      { emoji: '🧘', name: '冥想', keywords: ['冥想', '瑜伽', '放松'] },
      { emoji: '🛀', name: '洗澡', keywords: ['洗澡', '沐浴', '放松'] },
      { emoji: '🛌', name: '睡觉', keywords: ['睡觉', '休息', '床'] },
      { emoji: '👭', name: '两个女人', keywords: ['朋友', '女性', '一起'] },
      { emoji: '👫', name: '男女', keywords: ['情侣', '朋友', '一起'] },
      { emoji: '👬', name: '两个男人', keywords: ['朋友', '男性', '一起'] },
      { emoji: '💏', name: '情侣亲亲', keywords: ['情侣', '亲吻', '爱'] },
      { emoji: '💑', name: '情侣', keywords: ['情侣', '爱', '一起'] },
      { emoji: '👪', name: '家庭', keywords: ['家庭', '家人', '亲子'] }
    ]
  },
  {
    id: 'animals',
    name: '🐾 动物与自然',
    emojis: [
      { emoji: '🐶', name: '狗', keywords: ['狗', '宠物', '汪星人'] },
      { emoji: '🐱', name: '猫', keywords: ['猫', '宠物', '喵星人'] },
      { emoji: '🐭', name: '老鼠', keywords: ['老鼠', '耗子', '动物'] },
      { emoji: '🐹', name: '仓鼠', keywords: ['仓鼠', '宠物', '可爱'] },
      { emoji: '🐰', name: '兔子', keywords: ['兔子', '兔', '可爱'] },
      { emoji: '🦊', name: '狐狸', keywords: ['狐狸', '动物', '狡猾'] },
      { emoji: '🐻', name: '熊', keywords: ['熊', '动物', '可爱'] },
      { emoji: '🐼', name: '熊猫', keywords: ['熊猫', '国宝', '可爱'] },
      { emoji: '🦝', name: '浣熊', keywords: ['浣熊', '动物', '可爱'] },
      { emoji: '🐮', name: '牛', keywords: ['牛', '奶牛', '农场'] },
      { emoji: '🐷', name: '猪', keywords: ['猪', '小猪', '农场'] },
      { emoji: '🐸', name: '青蛙', keywords: ['青蛙', '蛙', '动物'] },
      { emoji: '🐵', name: '猴子', keywords: ['猴子', '猴', '动物'] },
      { emoji: '🙈', name: '非礼勿视', keywords: ['猴子', '捂眼', '不看'] },
      { emoji: '🙉', name: '非礼勿听', keywords: ['猴子', '捂耳', '不听'] },
      { emoji: '🙊', name: '非礼勿言', keywords: ['猴子', '捂嘴', '不说'] },
      { emoji: '🐒', name: '猩猩', keywords: ['猩猩', '猴子', '动物'] },
      { emoji: '🐔', name: '鸡', keywords: ['鸡', '公鸡', '农场'] },
      { emoji: '🐧', name: '企鹅', keywords: ['企鹅', '南极', '动物'] },
      { emoji: '🐦', name: '鸟', keywords: ['鸟', '小鸟', '飞'] },
      { emoji: '🐤', name: '小鸡', keywords: ['小鸡', '可爱', '农场'] },
      { emoji: '🐣', name: '破壳', keywords: ['鸡蛋', '孵化', '出生'] },
      { emoji: '🐥', name: '小黄鸡', keywords: ['小鸡', '可爱', '农场'] },
      { emoji: '🦆', name: '鸭子', keywords: ['鸭子', '鸭', '动物'] },
      { emoji: '🦅', name: '鹰', keywords: ['鹰', '雕', '猛禽'] },
      { emoji: '🦉', name: '猫头鹰', keywords: ['猫头鹰', '智慧', '夜'] },
      { emoji: '🦇', name: '蝙蝠', keywords: ['蝙蝠', '夜', '动物'] },
      { emoji: '🐺', name: '狼', keywords: ['狼', '动物', '凶猛'] },
      { emoji: '🐗', name: '野猪', keywords: ['野猪', '猪', '动物'] },
      { emoji: '🐴', name: '马', keywords: ['马', '骑马', '动物'] },
      { emoji: '🦄', name: '独角兽', keywords: ['独角兽', '魔法', '可爱'] },
      { emoji: '🐝', name: '蜜蜂', keywords: ['蜜蜂', '蜂蜜', '昆虫'] },
      { emoji: '🐛', name: '毛毛虫', keywords: ['虫子', '毛毛虫', '昆虫'] },
      { emoji: '🦋', name: '蝴蝶', keywords: ['蝴蝶', '美丽', '昆虫'] },
      { emoji: '🐌', name: '蜗牛', keywords: ['蜗牛', '慢', '动物'] },
      { emoji: '🪱', name: '蚯蚓', keywords: ['蚯蚓', '虫子', '土壤'] },
      { emoji: '🐞', name: '瓢虫', keywords: ['瓢虫', '昆虫', '可爱'] },
      { emoji: '🐜', name: '蚂蚁', keywords: ['蚂蚁', '昆虫', '小'] },
      { emoji: '🦟', name: '蚊子', keywords: ['蚊子', '昆虫', '咬'] },
      { emoji: '🦗', name: '蟋蟀', keywords: ['蟋蟀', '昆虫', '叫'] },
      { emoji: '🕷️', name: '蜘蛛', keywords: ['蜘蛛', '网', '昆虫'] },
      { emoji: '🦂', name: '蝎子', keywords: ['蝎子', '毒', '动物'] },
      { emoji: '🐢', name: '乌龟', keywords: ['乌龟', '慢', '长寿'] },
      { emoji: '🐍', name: '蛇', keywords: ['蛇', '毒', '爬行动物'] },
      { emoji: '🦎', name: '蜥蜴', keywords: ['蜥蜴', '爬行动物', '动物'] },
      { emoji: '🦖', name: '霸王龙', keywords: ['恐龙', '霸王龙', '史前'] },
      { emoji: '🦕', name: '梁龙', keywords: ['恐龙', '梁龙', '史前'] },
      { emoji: '🐙', name: '章鱼', keywords: ['章鱼', '八爪鱼', '海洋'] },
      { emoji: '🦑', name: '鱿鱼', keywords: ['鱿鱼', '乌贼', '海洋'] },
      { emoji: '🦐', name: '虾', keywords: ['虾', '海鲜', '海洋'] },
      { emoji: '🦞', name: '龙虾', keywords: ['龙虾', '海鲜', '海洋'] },
      { emoji: '🦀', name: '螃蟹', keywords: ['螃蟹', '蟹', '海洋'] },
      { emoji: '🐡', name: '河豚', keywords: ['河豚', '鱼', '海洋'] },
      { emoji: '🐠', name: '热带鱼', keywords: ['鱼', '热带', '海洋'] },
      { emoji: '🐟', name: '鱼', keywords: ['鱼', '海洋', '游泳'] },
      { emoji: '🐬', name: '海豚', keywords: ['海豚', '聪明', '海洋'] },
      { emoji: '🐳', name: '鲸鱼喷水', keywords: ['鲸鱼', '喷水', '海洋'] },
      { emoji: '🐋', name: '鲸鱼', keywords: ['鲸鱼', '巨大', '海洋'] },
      { emoji: '🦈', name: '鲨鱼', keywords: ['鲨鱼', '凶猛', '海洋'] },
      { emoji: '🐊', name: '鳄鱼', keywords: ['鳄鱼', '凶猛', '动物'] },
      { emoji: '🐅', name: '老虎', keywords: ['老虎', '虎', '凶猛'] },
      { emoji: '🐆', name: '豹子', keywords: ['豹子', '猎豹', '凶猛'] },
      { emoji: '🐃', name: '水牛', keywords: ['牛', '水牛', '动物'] },
      { emoji: '🐂', name: '公牛', keywords: ['牛', '公牛', '强壮'] },
      { emoji: '🐄', name: '奶牛', keywords: ['牛', '奶牛', '牛奶'] },
      { emoji: '🦬', name: '野牛', keywords: ['野牛', '牛', '动物'] },
      { emoji: '🐪', name: '骆驼', keywords: ['骆驼', '沙漠', '动物'] },
      { emoji: '🐫', name: '双峰驼', keywords: ['骆驼', '沙漠', '双峰'] },
      { emoji: '🦙', name: '羊驼', keywords: ['羊驼', '草泥马', '可爱'] },
      { emoji: '🦒', name: '长颈鹿', keywords: ['长颈鹿', '高', '动物'] },
      { emoji: '🐘', name: '大象', keywords: ['大象', '象', '大'] },
      { emoji: '🦏', name: '犀牛', keywords: ['犀牛', '动物', '角'] },
      { emoji: '🦛', name: '河马', keywords: ['河马', '动物', '大'] },
      { emoji: '🐐', name: '山羊', keywords: ['山羊', '羊', '动物'] },
      { emoji: '🐑', name: '绵羊', keywords: ['绵羊', '羊', '羊毛'] },
      { emoji: '🐏', name: '公羊', keywords: ['公羊', '羊', '动物'] },
      { emoji: '🦌', name: '鹿', keywords: ['鹿', '梅花鹿', '动物'] },
      { emoji: '🥀', name: '枯萎的花', keywords: ['枯萎', '花', '凋谢'] },
      { emoji: '💐', name: '花束', keywords: ['花束', '花', '礼物'] },
      { emoji: '🌸', name: '樱花', keywords: ['樱花', '春天', '日本'] },
      { emoji: '💮', name: '白花', keywords: ['花', '白色', '装饰'] },
      { emoji: '🏵️', name: '花环', keywords: ['花', '花环', '装饰'] },
      { emoji: '🌹', name: '玫瑰', keywords: ['玫瑰', '花', '爱情'] },
      { emoji: '🥀', name: '枯萎', keywords: ['枯萎', '花', '凋谢'] },
      { emoji: '🌺', name: '扶桑花', keywords: ['花', '夏威夷', '美丽'] },
      { emoji: '🌻', name: '向日葵', keywords: ['向日葵', '太阳', '花'] },
      { emoji: '🌼', name: '黄花', keywords: ['花', '黄色', '春天'] },
      { emoji: '🌷', name: '郁金香', keywords: ['郁金香', '花', '春天'] },
      { emoji: '🌱', name: '幼苗', keywords: ['种子', '发芽', '生长'] },
      { emoji: '🌲', name: '松树', keywords: ['树', '松树', '常青'] },
      { emoji: '🌳', name: '落叶树', keywords: ['树', '绿叶', '自然'] },
      { emoji: '🌴', name: '棕榈树', keywords: ['树', '棕榈', '热带'] },
      { emoji: '🌵', name: '仙人掌', keywords: ['仙人掌', '沙漠', '植物'] },
      { emoji: '🌾', name: '稻穗', keywords: ['稻子', '麦子', '丰收'] },
      { emoji: '🌿', name: '药草', keywords: ['草', '植物', '绿色'] },
      { emoji: '☘️', name: '三叶草', keywords: ['三叶草', '幸运', '爱尔兰'] },
      { emoji: '🍀', name: '四叶草', keywords: ['四叶草', '幸运', '草'] },
      { emoji: '🍁', name: '枫叶', keywords: ['枫叶', '秋天', '加拿大'] },
      { emoji: '🍂', name: '落叶', keywords: ['落叶', '秋天', '树叶'] },
      { emoji: '🍃', name: '风中落叶', keywords: ['风', '叶子', '飘动'] },
      { emoji: '🌍', name: '地球非洲', keywords: ['地球', '世界', '非洲'] },
      { emoji: '🌎', name: '地球美洲', keywords: ['地球', '世界', '美洲'] },
      { emoji: '🌏', name: '地球亚洲', keywords: ['地球', '世界', '亚洲'] },
      { emoji: '🌙', name: '月亮', keywords: ['月亮', '月球', '夜晚'] },
      { emoji: '🌚', name: '月亮脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌛', name: '新月脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌜', name: '残月脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌞', name: '太阳脸', keywords: ['太阳', '脸', '阳光'] },
      { emoji: '⭐', name: '星星', keywords: ['星星', '星光', '闪亮'] },
      { emoji: '🌟', name: '闪亮星星', keywords: ['星星', '闪亮', '发光'] },
      { emoji: '✨', name: '闪烁', keywords: ['闪亮', '发光', '魔法'] },
      { emoji: '⚡', name: '闪电', keywords: ['闪电', '电', '快速'] },
      { emoji: '🔥', name: '火', keywords: ['火', '热', '燃烧'] },
      { emoji: '💧', name: '水滴', keywords: ['水', '水滴', '雨'] },
      { emoji: '🌊', name: '海浪', keywords: ['海浪', '大海', '水'] },
      { emoji: '🌫️', name: '雾', keywords: ['雾', '朦胧', '天气'] },
      { emoji: '🌪️', name: '龙卷风', keywords: ['龙卷风', '风', '灾难'] },
      { emoji: '🌧️', name: '下雨', keywords: ['雨', '下雨', '天气'] },
      { emoji: '⛈️', name: '雷雨天', keywords: ['雷雨', '闪电', '下雨'] },
      { emoji: '🌤️', name: '晴转多云', keywords: ['晴天', '多云', '太阳'] },
      { emoji: '🌥️', name: '多云', keywords: ['多云', '云', '天气'] },
      { emoji: '🌦️', name: '阵雨', keywords: ['阵雨', '下雨', '太阳'] },
      { emoji: '🌈', name: '彩虹', keywords: ['彩虹', '七彩', '雨后'] },
      { emoji: '☀️', name: '太阳', keywords: ['太阳', '晴天', '阳光'] },
      { emoji: '🌝', name: '满月脸', keywords: ['月亮', '脸', '圆'] },
      { emoji: '🌞', name: '太阳', keywords: ['太阳', '阳光', '晴天'] }
    ]
  },
  {
    id: 'food',
    name: '🍕 食物与饮料',
    emojis: [
      { emoji: '🍇', name: '葡萄', keywords: ['葡萄', '水果', '紫色'] },
      { emoji: '🍈', name: '甜瓜', keywords: ['甜瓜', '哈密瓜', '水果'] },
      { emoji: '🍉', name: '西瓜', keywords: ['西瓜', '水果', '夏天'] },
      { emoji: '🍊', name: '橘子', keywords: ['橘子', '橙子', '水果'] },
      { emoji: '🍋', name: '柠檬', keywords: ['柠檬', '酸', '水果'] },
      { emoji: '🍌', name: '香蕉', keywords: ['香蕉', '水果', '黄色'] },
      { emoji: '🍍', name: '菠萝', keywords: ['菠萝', '凤梨', '水果'] },
      { emoji: '🥭', name: '芒果', keywords: ['芒果', '水果', '热带'] },
      { emoji: '🍎', name: '红苹果', keywords: ['苹果', '水果', '红色'] },
      { emoji: '🍏', name: '青苹果', keywords: ['苹果', '水果', '绿色'] },
      { emoji: '🍐', name: '梨', keywords: ['梨', '水果', '鸭梨'] },
      { emoji: '🍑', name: '桃子', keywords: ['桃子', '水果', '粉色'] },
      { emoji: '🍒', name: '樱桃', keywords: ['樱桃', '车厘子', '水果'] },
      { emoji: '🍓', name: '草莓', keywords: ['草莓', '水果', '红色'] },
      { emoji: '🥝', name: '猕猴桃', keywords: ['猕猴桃', '奇异果', '水果'] },
      { emoji: '🍅', name: '番茄', keywords: ['番茄', '西红柿', '蔬菜'] },
      { emoji: '🍆', name: '茄子', keywords: ['茄子', '蔬菜', '紫色'] },
      { emoji: '🥑', name: '牛油果', keywords: ['牛油果', '鳄梨', '健康'] },
      { emoji: '🥦', name: '西兰花', keywords: ['西兰花', '蔬菜', '绿色'] },
      { emoji: '🥬', name: '白菜', keywords: ['白菜', '蔬菜', '绿色'] },
      { emoji: '🥒', name: '黄瓜', keywords: ['黄瓜', '蔬菜', '绿色'] },
      { emoji: '🌶️', name: '辣椒', keywords: ['辣椒', '辣', '红色'] },
      { emoji: '🌽', name: '玉米', keywords: ['玉米', '粗粮', '黄色'] },
      { emoji: '🥕', name: '胡萝卜', keywords: ['胡萝卜', '萝卜', '橙色'] },
      { emoji: '🧅', name: '洋葱', keywords: ['洋葱', '蔬菜', '葱'] },
      { emoji: '🧄', name: '大蒜', keywords: ['大蒜', '蒜', '调料'] },
      { emoji: '🥔', name: '土豆', keywords: ['土豆', '马铃薯', '蔬菜'] },
      { emoji: '🍠', name: '地瓜', keywords: ['地瓜', '红薯', '甜'] },
      { emoji: '🥐', name: '可颂', keywords: ['可颂', '牛角包', '面包'] },
      { emoji: '🥯', name: '贝果', keywords: ['贝果', '面包', '早餐'] },
      { emoji: '🍞', name: '面包', keywords: ['面包', '吐司', '早餐'] },
      { emoji: '🥖', name: '法棍', keywords: ['法棍', '面包', '法国'] },
      { emoji: '🧈', name: '黄油', keywords: ['黄油', '奶油', '早餐'] },
      { emoji: '🧂', name: '盐', keywords: ['盐', '调料', '咸'] },
      { emoji: '🥞', name: '松饼', keywords: ['松饼', '煎饼', '早餐'] },
      { emoji: '🧇', name: '华夫饼', keywords: ['华夫饼', '饼干', '早餐'] },
      { emoji: '🍳', name: '煎蛋', keywords: ['鸡蛋', '煎蛋', '早餐'] },
      { emoji: '🥚', name: '鸡蛋', keywords: ['鸡蛋', '蛋', '早餐'] },
      { emoji: '🧀', name: '奶酪', keywords: ['奶酪', '芝士', '乳制品'] },
      { emoji: '🥖', name: '法棍', keywords: ['法棍', '面包', '法国'] },
      { emoji: '🍗', name: '鸡腿', keywords: ['鸡肉', '鸡腿', '肉'] },
      { emoji: '🍖', name: '排骨', keywords: ['肉', '排骨', '烧烤'] },
      { emoji: '🦴', name: '骨头', keywords: ['骨头', '骨骼', '肉'] },
      { emoji: '🌭', name: '热狗', keywords: ['热狗', '香肠', '快餐'] },
      { emoji: '🍔', name: '汉堡', keywords: ['汉堡', '汉堡包', '快餐'] },
      { emoji: '🍟', name: '薯条', keywords: ['薯条', '土豆', '快餐'] },
      { emoji: '🍕', name: '披萨', keywords: ['披萨', '比萨', '意大利'] },
      { emoji: '🥪', name: '三明治', keywords: ['三明治', '三文治', '早餐'] },
      { emoji: '🌮', name: '墨西哥卷', keywords: ['墨西哥卷', 'taco', '墨西哥'] },
      { emoji: '🌯', name: '卷饼', keywords: ['卷饼', 'burrito', '墨西哥'] },
      { emoji: '🥙', name: '夹饼', keywords: ['夹饼', '烤肉', '中东'] },
      { emoji: '🧆', name: '炸豆丸', keywords: ['炸豆丸', '中东', '素食'] },
      { emoji: '🥚', name: '鸡蛋', keywords: ['鸡蛋', '蛋', '早餐'] },
      { emoji: '🥘', name: '海鲜饭', keywords: ['海鲜饭', 'paella', '西班牙'] },
      { emoji: '🍝', name: '意面', keywords: ['意面', '意大利面', '面条'] },
      { emoji: '🥫', name: '罐头', keywords: ['罐头', '番茄酱', '食品'] },
      { emoji: '🍜', name: '面条', keywords: ['面条', '拉面', '日本'] },
      { emoji: '🍲', name: '火锅', keywords: ['火锅', '汤锅', '热'] },
      { emoji: '🍛', name: '咖喱饭', keywords: ['咖喱', '饭', '印度'] },
      { emoji: '🍣', name: '寿司', keywords: ['寿司', '日本', '鱼'] },
      { emoji: '🍱', name: '便当', keywords: ['便当', '盒饭', '日本'] },
      { emoji: '🥟', name: '饺子', keywords: ['饺子', '中国', '春节'] },
      { emoji: '🥠', name: '幸运饼干', keywords: ['幸运饼干', '中餐', '预测'] },
      { emoji: '🥡', name: '外卖盒', keywords: ['外卖', '打包', '中餐'] },
      { emoji: '🦀', name: '螃蟹', keywords: ['螃蟹', '蟹', '海鲜'] },
      { emoji: '🦞', name: '龙虾', keywords: ['龙虾', '海鲜', '大餐'] },
      { emoji: '🦐', name: '虾', keywords: ['虾', '虾仁', '海鲜'] },
      { emoji: '🦑', name: '鱿鱼', keywords: ['鱿鱼', '乌贼', '海鲜'] },
      { emoji: '🐙', name: '章鱼', keywords: ['章鱼', '八爪鱼', '海鲜'] },
      { emoji: '🦈', name: '鲨鱼', keywords: ['鲨鱼', '鱼', '海洋'] },
      { emoji: '🐡', name: '河豚', keywords: ['河豚', '鱼', '海鲜'] },
      { emoji: '🐠', name: '热带鱼', keywords: ['鱼', '热带', '海洋'] },
      { emoji: '🐟', name: '鱼', keywords: ['鱼', '海洋', '游泳'] },
      { emoji: '🐬', name: '海豚', keywords: ['海豚', '聪明', '海洋'] },
      { emoji: '🐳', name: '鲸鱼', keywords: ['鲸鱼', '巨大', '海洋'] },
      { emoji: '🐋', name: '抹香鲸', keywords: ['鲸鱼', '巨大', '海洋'] },
      { emoji: '🦭', name: '海豹', keywords: ['海豹', '海狮', '海洋'] },
      { emoji: '🍦', name: '冰淇淋', keywords: ['冰淇淋', '雪糕', '冷'] },
      { emoji: '🍧', name: '冰沙', keywords: ['冰沙', '刨冰', '冷'] },
      { emoji: '🍨', name: '冰淇淋碗', keywords: ['冰淇淋', '碗', '甜品'] },
      { emoji: '🍩', name: '甜甜圈', keywords: ['甜甜圈', '甜点', '圈'] },
      { emoji: '🍪', name: '饼干', keywords: ['饼干', '曲奇', '零食'] },
      { emoji: '🎂', name: '生日蛋糕', keywords: ['蛋糕', '生日', '庆祝'] },
      { emoji: '🍰', name: '蛋糕', keywords: ['蛋糕', '甜品', '奶油'] },
      { emoji: '🧁', name: '杯子蛋糕', keywords: ['杯子蛋糕', '纸杯蛋糕', '甜品'] },
      { emoji: '🥧', name: '派', keywords: ['派', '馅饼', '甜品'] },
      { emoji: '🍫', name: '巧克力', keywords: ['巧克力', '可可', '零食'] },
      { emoji: '🍬', name: '糖果', keywords: ['糖果', '糖', '甜'] },
      { emoji: '🍭', name: '棒棒糖', keywords: ['棒棒糖', '糖', '甜'] },
      { emoji: '🍮', name: '布丁', keywords: ['布丁', '甜品', '奶油'] },
      { emoji: '🍯', name: '蜂蜜', keywords: ['蜂蜜', '甜', '蜂'] },
      { emoji: '🍼', name: '奶瓶', keywords: ['奶瓶', '牛奶', '婴儿'] },
      { emoji: '🥛', name: '牛奶', keywords: ['牛奶', '奶', '饮品'] },
      { emoji: '☕', name: '咖啡', keywords: ['咖啡', '提神', '热饮'] },
      { emoji: '🍵', name: '茶', keywords: ['茶', '绿茶', '饮品'] },
      { emoji: '🍶', name: '清酒', keywords: ['清酒', '日本', '酒'] },
      { emoji: '🍾', name: '开香槟', keywords: ['香槟', '庆祝', '酒'] },
      { emoji: '🍷', name: '红酒', keywords: ['红酒', '葡萄酒', '酒'] },
      { emoji: '🍸', name: '鸡尾酒', keywords: ['鸡尾酒', '酒', '酒吧'] },
      { emoji: '🍹', name: '热带饮料', keywords: ['饮料', '热带', '果汁'] },
      { emoji: '🍺', name: '啤酒', keywords: ['啤酒', '酒', '干杯'] },
      { emoji: '🍻', name: '干杯', keywords: ['干杯', '啤酒', '庆祝'] },
      { emoji: '🥂', name: '碰杯', keywords: ['碰杯', '香槟', '庆祝'] },
      { emoji: '🥃', name: '威士忌', keywords: ['威士忌', '酒', '烈酒'] },
      { emoji: '🥤', name: '可乐杯', keywords: ['可乐', '饮料', '汽水'] },
      { emoji: '🧋', name: '珍珠奶茶', keywords: ['奶茶', '珍珠', '饮料'] },
      { emoji: '🧃', name: '饮料盒', keywords: ['饮料', '果汁', '盒装'] },
      { emoji: '🧉', name: '马黛茶', keywords: ['马黛茶', '阿根廷', '饮品'] },
      { emoji: '🧊', name: '冰块', keywords: ['冰', '冰块', '冷'] },
      { emoji: '🥢', name: '筷子', keywords: ['筷子', '餐具', '中国'] },
      { emoji: '🍽️', name: '餐具', keywords: ['餐具', '刀叉', '吃饭'] },
      { emoji: '🍴', name: '刀叉', keywords: ['刀叉', '餐具', '吃饭'] },
      { emoji: '🥄', name: '勺子', keywords: ['勺子', '汤匙', '餐具'] }
    ]
  },
  {
    id: 'activities',
    name: '⚽ 活动与运动',
    emojis: [
      { emoji: '🎃', name: '南瓜灯', keywords: ['万圣节', '南瓜', '节日'] },
      { emoji: '🎄', name: '圣诞树', keywords: ['圣诞节', '树', '节日'] },
      { emoji: '🎆', name: '烟花', keywords: ['烟花', '过年', '庆祝'] },
      { emoji: '🎇', name: '烟花棒', keywords: ['烟花', '仙女棒', '庆祝'] },
      { emoji: '🧨', name: '鞭炮', keywords: ['鞭炮', '过年', '爆炸'] },
      { emoji: '✨', name: '闪亮', keywords: ['闪亮', '星星', '发光'] },
      { emoji: '🎈', name: '气球', keywords: ['气球', '派对', '生日'] },
      { emoji: '🎉', name: '拉炮', keywords: ['庆祝', '派对', '开心'] },
      { emoji: '🎊', name: '庆祝', keywords: ['庆祝', '派对', '开心'] },
      { emoji: '🎋', name: '七夕树', keywords: ['七夕', '日本', '愿望'] },
      { emoji: '🎍', name: '门松', keywords: ['日本', '新年', '装饰'] },
      { emoji: '🎎', name: '日本人偶', keywords: ['人偶', '日本', '女孩节'] },
      { emoji: '🎏', name: '鲤鱼旗', keywords: ['鲤鱼旗', '日本', '男孩节'] },
      { emoji: '🎐', name: '风铃', keywords: ['风铃', '夏天', '日本'] },
      { emoji: '🎑', name: '赏月', keywords: ['赏月', '月亮', '秋天'] },
      { emoji: '🧧', name: '红包', keywords: ['红包', '过年', '礼物'] },
      { emoji: '🎀', name: '蝴蝶结', keywords: ['蝴蝶结', '装饰', '可爱'] },
      { emoji: '🎁', name: '礼物', keywords: ['礼物', '礼品', '生日'] },
      { emoji: '🎗️', name: '黄丝带', keywords: ['丝带', '纪念', '希望'] },
      { emoji: '🎟️', name: '门票', keywords: ['门票', '票', '入场'] },
      { emoji: '🎫', name: '票', keywords: ['票', '门票', '入场'] },
      { emoji: '🎖️', name: '勋章', keywords: ['勋章', '奖章', '荣誉'] },
      { emoji: '🏆', name: '奖杯', keywords: ['奖杯', '冠军', '获奖'] },
      { emoji: '🏅', name: '奖牌', keywords: ['奖牌', '奖章', '荣誉'] },
      { emoji: '🥇', name: '金牌', keywords: ['金牌', '冠军', '第一'] },
      { emoji: '🥈', name: '银牌', keywords: ['银牌', '亚军', '第二'] },
      { emoji: '🥉', name: '铜牌', keywords: ['铜牌', '季军', '第三'] },
      { emoji: '⚽', name: '足球', keywords: ['足球', '球', '运动'] },
      { emoji: '🏀', name: '篮球', keywords: ['篮球', '球', '运动'] },
      { emoji: '🏈', name: '橄榄球', keywords: ['橄榄球', '球', '运动'] },
      { emoji: '⚾', name: '棒球', keywords: ['棒球', '球', '运动'] },
      { emoji: '🥎', name: '垒球', keywords: ['垒球', '球', '运动'] },
      { emoji: '🎾', name: '网球', keywords: ['网球', '球', '运动'] },
      { emoji: '🏐', name: '排球', keywords: ['排球', '球', '运动'] },
      { emoji: '🏉', name: '澳式橄榄球', keywords: ['橄榄球', '球', '运动'] },
      { emoji: '🎱', name: '台球', keywords: ['台球', '桌球', '8号球'] },
      { emoji: '🎳', name: '保龄球', keywords: ['保龄球', '球', '运动'] },
      { emoji: '🏏', name: '板球', keywords: ['板球', '球', '运动'] },
      { emoji: '🏑', name: '曲棍球', keywords: ['曲棍球', '球', '运动'] },
      { emoji: '🏒', name: '冰球', keywords: ['冰球', '球', '冬天'] },
      { emoji: '🥍', name: '袋棍球', keywords: ['袋棍球', '球', '运动'] },
      { emoji: '🏓', name: '乒乓球', keywords: ['乒乓球', '乒乓', '运动'] },
      { emoji: '🏸', name: '羽毛球', keywords: ['羽毛球', '球', '运动'] },
      { emoji: '🥊', name: '拳击', keywords: ['拳击', '手套', '运动'] },
      { emoji: '🥋', name: '道服', keywords: ['跆拳道', '空手道', '武术'] },
      { emoji: '🥅', name: '球门', keywords: ['球门', '进球', '运动'] },
      { emoji: '⛳', name: '高尔夫球洞', keywords: ['高尔夫', '球洞', '运动'] },
      { emoji: '🎣', name: '钓鱼', keywords: ['钓鱼', '鱼竿', '休闲'] },
      { emoji: '🤿', name: '潜水面罩', keywords: ['潜水', '游泳', '水下'] },
      { emoji: '🎽', name: '运动背心', keywords: ['运动', '背心', '跑步'] },
      { emoji: '🎿', name: '滑雪板', keywords: ['滑雪', '冬天', '运动'] },
      { emoji: '🛷', name: '雪橇', keywords: ['雪橇', '冬天', '滑雪'] },
      { emoji: '🥌', name: '冰壶', keywords: ['冰壶', '冬天', '运动'] },
      { emoji: '🎯', name: '靶心', keywords: ['靶心', '射箭', '目标'] },
      { emoji: '🎪', name: '马戏团', keywords: ['马戏团', '帐篷', '表演'] },
      { emoji: '🎭', name: '戏剧面具', keywords: ['戏剧', '面具', '表演'] },
      { emoji: '🎨', name: '调色盘', keywords: ['画画', '艺术', '创意'] },
      { emoji: '🎬', name: '场记板', keywords: ['电影', '导演', '拍戏'] },
      { emoji: '🎤', name: '麦克风', keywords: ['唱歌', '麦克风', '音乐'] },
      { emoji: '🎧', name: '耳机', keywords: ['耳机', '音乐', '听歌'] },
      { emoji: '🎼', name: '乐谱', keywords: ['音乐', '乐谱', '音符'] },
      { emoji: '🎹', name: '钢琴', keywords: ['钢琴', '音乐', '乐器'] },
      { emoji: '🎷', name: '萨克斯', keywords: ['萨克斯', '音乐', '乐器'] },
      { emoji: '🎺', name: '小号', keywords: ['小号', '音乐', '乐器'] },
      { emoji: '🎸', name: '吉他', keywords: ['吉他', '音乐', '乐器'] },
      { emoji: '🪕', name: '班卓琴', keywords: ['班卓琴', '音乐', '乐器'] },
      { emoji: '🎻', name: '小提琴', keywords: ['小提琴', '音乐', '乐器'] },
      { emoji: '🪗', name: '手风琴', keywords: ['手风琴', '音乐', '乐器'] },
      { emoji: '🎤', name: '麦克风', keywords: ['唱歌', '麦克风', '音乐'] },
      { emoji: '🎧', name: '耳机', keywords: ['耳机', '音乐', '听歌'] },
      { emoji: '🎼', name: '乐谱', keywords: ['音乐', '乐谱', '音符'] },
      { emoji: '🎹', name: '钢琴', keywords: ['钢琴', '音乐', '乐器'] }
    ]
  },
  {
    id: 'objects',
    name: '💼 物品与符号',
    emojis: [
      { emoji: '⌚', name: '手表', keywords: ['手表', '时间', '看时间'] },
      { emoji: '📱', name: '手机', keywords: ['手机', '电话', '移动'] },
      { emoji: '💻', name: '电脑', keywords: ['电脑', '笔记本', '科技'] },
      { emoji: '🖥️', name: '台式电脑', keywords: ['电脑', '台式', '显示器'] },
      { emoji: '🖨️', name: '打印机', keywords: ['打印机', '打印', '办公'] },
      { emoji: '🖱️', name: '鼠标', keywords: ['鼠标', '电脑', '点击'] },
      { emoji: '🖲️', name: '游戏手柄', keywords: ['游戏手柄', '游戏', '控制'] },
      { emoji: '🗜️', name: '压缩', keywords: ['压缩', '解压', '文件'] },
      { emoji: '💽', name: '软盘', keywords: ['软盘', '存储', '复古'] },
      { emoji: '💾', name: '硬盘', keywords: ['硬盘', '存储', '保存'] },
      { emoji: '💿', name: '光盘', keywords: ['光盘', 'CD', '音乐'] },
      { emoji: '📀', name: 'DVD', keywords: ['DVD', '光盘', '电影'] },
      { emoji: '📼', name: '录像带', keywords: ['录像带', 'VHS', '复古'] },
      { emoji: '📷', name: '相机', keywords: ['相机', '拍照', '照片'] },
      { emoji: '📸', name: '拍立得', keywords: ['拍照', '照片', '相机'] },
      { emoji: '📹', name: '摄像机', keywords: ['摄像机', '录像', '视频'] },
      { emoji: '🎥', name: '电影摄像机', keywords: ['电影', '摄像机', '拍摄'] },
      { emoji: '📽️', name: '放映机', keywords: ['放映机', '电影', '投影'] },
      { emoji: '🎞️', name: '胶片', keywords: ['胶片', '电影', '帧'] },
      { emoji: '📞', name: '电话', keywords: ['电话', '通话', '联系'] },
      { emoji: '☎️', name: '座机', keywords: ['电话', '座机', '固定'] },
      { emoji: '📟', name: '传呼机', keywords: ['传呼机', 'BB机', '复古'] },
      { emoji: '📠', name: '传真机', keywords: ['传真', '传真机', '办公'] },
      { emoji: '📺', name: '电视', keywords: ['电视', '看电视', '视频'] },
      { emoji: '📻', name: '收音机', keywords: ['收音机', '广播', '听'] },
      { emoji: '🎙️', name: '录音笔', keywords: ['录音', '麦克风', '声音'] },
      { emoji: '🎚️', name: '音量调节', keywords: ['音量', '调节', '声音'] },
      { emoji: '🎛️', name: '调音台', keywords: ['调音台', '音乐', '控制'] },
      { emoji: '🧭', name: '指南针', keywords: ['指南针', '导航', '方向'] },
      { emoji: '🔋', name: '电池', keywords: ['电池', '电量', '充电'] },
      { emoji: '🔌', name: '插头', keywords: ['插头', '充电', '电源'] },
      { emoji: '💡', name: '灯泡', keywords: ['灯泡', '创意', '想法'] },
      { emoji: '🔦', name: '手电筒', keywords: ['手电筒', '光', '照明'] },
      { emoji: '🕯️', name: '蜡烛', keywords: ['蜡烛', '光', '浪漫'] },
      { emoji: '🪔', name: '油灯', keywords: ['油灯', '灯', '印度'] },
      { emoji: '📡', name: '卫星', keywords: ['卫星', '信号', '天线'] },
      { emoji: '💻', name: '笔记本电脑', keywords: ['电脑', '笔记本', '办公'] },
      { emoji: '📚', name: '书本', keywords: ['书', '看书', '学习'] },
      { emoji: '📖', name: '打开的书', keywords: ['书', '阅读', '学习'] },
      { emoji: '📕', name: '红皮书', keywords: ['书', '红色', '封面'] },
      { emoji: '📗', name: '绿皮书', keywords: ['书', '绿色', '封面'] },
      { emoji: '📘', name: '蓝皮书', keywords: ['书', '蓝色', '封面'] },
      { emoji: '📙', name: '橙皮书', keywords: ['书', '橙色', '封面'] },
      { emoji: '📓', name: '笔记本', keywords: ['笔记本', '记事本', '写'] },
      { emoji: '📔', name: '精装笔记本', keywords: ['笔记本', '精装', '写'] },
      { emoji: '📒', name: '账本', keywords: ['账本', '记账', '财务'] },
      { emoji: '📃', name: '纸', keywords: ['纸', '文件', '文档'] },
      { emoji: '📜', name: '卷轴', keywords: ['卷轴', '古老', '文献'] },
      { emoji: '📋', name: '剪贴板', keywords: ['剪贴板', '复制', '粘贴'] },
      { emoji: '📁', name: '文件夹', keywords: ['文件夹', '文件', '整理'] },
      { emoji: '📂', name: '打开文件夹', keywords: ['文件夹', '打开', '文件'] },
      { emoji: '🗂️', name: '文件盒', keywords: ['文件盒', '分类', '整理'] },
      { emoji: '📅', name: '日历', keywords: ['日历', '日期', '时间'] },
      { emoji: '📆', name: '日程本', keywords: ['日程', '计划', '安排'] },
      { emoji: '🗒️', name: '记事本', keywords: ['记事本', '笔记', '写'] },
      { emoji: '🗓️', name: '日程', keywords: ['日程', '日历', '安排'] },
      { emoji: '📇', name: '名片夹', keywords: ['名片', '联系', '名片夹'] },
      { emoji: '📈', name: '上升趋势', keywords: ['上升', '增长', '股票'] },
      { emoji: '📉', name: '下降趋势', keywords: ['下降', '下跌', '股票'] },
      { emoji: '📊', name: '柱状图', keywords: ['图表', '数据', '统计'] },
      { emoji: '📋', name: '清单', keywords: ['清单', '列表', '任务'] },
      { emoji: '📌', name: '图钉', keywords: ['图钉', '固定', '标记'] },
      { emoji: '📍', name: '定位', keywords: ['定位', '位置', '地图'] },
      { emoji: '📎', name: '回形针', keywords: ['回形针', '别针', '固定'] },
      { emoji: '📐', name: '三角尺', keywords: ['尺子', '三角', '测量'] },
      { emoji: '📏', name: '直尺', keywords: ['尺子', '直尺', '测量'] },
      { emoji: '🔒', name: '锁', keywords: ['锁', '安全', '锁定'] },
      { emoji: '🔓', name: '解锁', keywords: ['解锁', '打开', '安全'] },
      { emoji: '🔏', name: '保密锁', keywords: ['锁', '保密', '安全'] },
      { emoji: '🔐', name: '钥匙', keywords: ['钥匙', '锁', '安全'] },
      { emoji: '🔑', name: '钥匙', keywords: ['钥匙', '开锁', '门'] },
      { emoji: '🔨', name: '锤子', keywords: ['锤子', '工具', '敲打'] },
      { emoji: '🪓', name: '斧头', keywords: ['斧头', '砍', '工具'] },
      { emoji: '💣', name: '炸弹', keywords: ['炸弹', '爆炸', '危险'] },
      { emoji: '🔪', name: '刀', keywords: ['刀', '切', '工具'] },
      { emoji: '🗡️', name: '匕首', keywords: ['匕首', '刀', '武器'] },
      { emoji: '🔫', name: '枪', keywords: ['枪', '武器', '射击'] },
      { emoji: '💊', name: '药丸', keywords: ['药丸', '药', '生病'] },
      { emoji: '💉', name: '打针', keywords: ['打针', '疫苗', '医院'] },
      { emoji: '🩸', name: '血滴', keywords: ['血', '流血', '医院'] },
      { emoji: '🩹', name: '创可贴', keywords: ['创可贴', '伤口', '医院'] },
      { emoji: '🩺', name: '听诊器', keywords: ['听诊器', '医生', '医院'] },
      { emoji: '💼', name: '公文包', keywords: ['公文包', '办公', '工作'] },
      { emoji: '👜', name: '手提包', keywords: ['手提包', '包', '时尚'] },
      { emoji: '👝', name: '零钱包', keywords: ['零钱包', '包', '钱'] },
      { emoji: '🛍️', name: '购物袋', keywords: ['购物', '袋子', '逛街'] },
      { emoji: '🎒', name: '书包', keywords: ['书包', '背包', '上学'] },
      { emoji: '👞', name: '男士鞋', keywords: ['鞋', '男士', '鞋子'] },
      { emoji: '👟', name: '运动鞋', keywords: ['鞋', '运动', '跑步'] },
      { emoji: '🥾', name: '登山鞋', keywords: ['鞋', '登山', '户外'] },
      { emoji: '🥿', name: '平底鞋', keywords: ['鞋', '平底', '女士'] },
      { emoji: '👠', name: '高跟鞋', keywords: ['鞋', '高跟', '时尚'] },
      { emoji: '👡', name: '凉鞋', keywords: ['鞋', '凉鞋', '夏天'] },
      { emoji: '🩰', name: '芭蕾舞鞋', keywords: ['鞋', '芭蕾', '舞蹈'] },
      { emoji: '👢', name: '靴子', keywords: ['靴子', '鞋', '冬天'] },
      { emoji: '👑', name: '皇冠', keywords: ['皇冠', '国王', '女王'] },
      { emoji: '👒', name: '女帽', keywords: ['帽子', '女士', '时尚'] },
      { emoji: '🎩', name: '礼帽', keywords: ['帽子', '礼帽', '绅士'] },
      { emoji: '🎓', name: '毕业帽', keywords: ['毕业', '帽子', '学生'] },
      { emoji: '🧢', name: '棒球帽', keywords: ['帽子', '棒球', '休闲'] },
      { emoji: '📿', name: '念珠', keywords: ['念珠', '祈祷', '宗教'] },
      { emoji: '💄', name: '口红', keywords: ['口红', '化妆', '美妆'] },
      { emoji: '💍', name: '戒指', keywords: ['戒指', '钻戒', '结婚'] },
      { emoji: '💎', name: '钻石', keywords: ['钻石', '宝石', '珍贵'] },
      { emoji: '🔮', name: '水晶球', keywords: ['水晶球', '魔法', '预测'] },
      { emoji: '📿', name: '项链', keywords: ['项链', '首饰', '珠宝'] },
      { emoji: '🎭', name: '面具', keywords: ['面具', '表演', '戏剧'] },
      { emoji: '🎨', name: '调色盘', keywords: ['画画', '艺术', '颜色'] },
      { emoji: '🎬', name: '拍电影', keywords: ['电影', '导演', '拍摄'] },
      { emoji: '🎤', name: '麦克风', keywords: ['唱歌', '话筒', '音乐'] },
      { emoji: '🎧', name: '耳机', keywords: ['耳机', '听歌', '音乐'] },
      { emoji: '🎼', name: '乐谱', keywords: ['音乐', '乐谱', '音符'] },
      { emoji: '🎹', name: '钢琴', keywords: ['钢琴', '乐器', '音乐'] },
      { emoji: '🎷', name: '萨克斯', keywords: ['萨克斯', '乐器', '音乐'] },
      { emoji: '🎺', name: '小号', keywords: ['小号', '乐器', '音乐'] },
      { emoji: '🎸', name: '吉他', keywords: ['吉他', '乐器', '音乐'] },
      { emoji: '🎻', name: '小提琴', keywords: ['小提琴', '乐器', '音乐'] },
      { emoji: '🥁', name: '鼓', keywords: ['鼓', '乐器', '音乐'] },
      { emoji: '🪘', name: '长鼓', keywords: ['鼓', '乐器', '非洲'] },
      { emoji: '🎬', name: '电影', keywords: ['电影', '视频', '影院'] }
    ]
  },
  {
    id: 'travel',
    name: '✈️ 旅行与地点',
    emojis: [
      { emoji: '🚗', name: '汽车', keywords: ['车', '汽车', '开车'] },
      { emoji: '🚕', name: '出租车', keywords: ['出租车', '的士', '打车'] },
      { emoji: '🚙', name: 'SUV', keywords: ['越野车', 'SUV', '汽车'] },
      { emoji: '🚌', name: '公交车', keywords: ['公交车', '巴士', '公共汽车'] },
      { emoji: '🚎', name: '电车', keywords: ['电车', '公交', '电动'] },
      { emoji: '🏎️', name: '赛车', keywords: ['赛车', '跑车', '速度'] },
      { emoji: '🚓', name: '警车', keywords: ['警车', '警察', '安全'] },
      { emoji: '🚑', name: '救护车', keywords: ['救护车', '医院', '急救'] },
      { emoji: '🚒', name: '消防车', keywords: ['消防车', '灭火', '救援'] },
      { emoji: '🚐', name: '面包车', keywords: ['面包车', '小巴', '货车'] },
      { emoji: '🚚', name: '货车', keywords: ['货车', '卡车', '运输'] },
      { emoji: '🚛', name: '卡车', keywords: ['卡车', '大货车', '运输'] },
      { emoji: '🚜', name: '拖拉机', keywords: ['拖拉机', '农场', '农业'] },
      { emoji: '🏍️', name: '摩托车', keywords: ['摩托车', '摩托', '机车'] },
      { emoji: '🛵', name: '电动车', keywords: ['电动车', '摩托', '轻便'] },
      { emoji: '🦽', name: '轮椅', keywords: ['轮椅', '残疾人', '无障碍'] },
      { emoji: '🦼', name: '电动轮椅', keywords: ['轮椅', '电动', '残疾人'] },
      { emoji: '🛺', name: '三轮车', keywords: ['三轮车', '嘟嘟车', '泰国'] },
      { emoji: '🚲', name: '自行车', keywords: ['自行车', '单车', '骑行'] },
      { emoji: '🛴', name: '滑板车', keywords: ['滑板车', '平衡车', '代步'] },
      { emoji: '🛹', name: '滑板', keywords: ['滑板', '轮滑', '运动'] },
      { emoji: '🛼', name: '旱冰鞋', keywords: ['旱冰鞋', '轮滑', '溜冰'] },
      { emoji: '🚏', name: '公交站', keywords: ['公交站', '车站', '站牌'] },
      { emoji: '🛣️', name: '高速公路', keywords: ['高速公路', '公路', '道路'] },
      { emoji: '🛤️', name: '铁轨', keywords: ['铁轨', '火车', '铁路'] },
      { emoji: '🛢️', name: '油桶', keywords: ['油桶', '石油', '汽油'] },
      { emoji: '⛽', name: '加油站', keywords: ['加油站', '加油', '汽油'] },
      { emoji: '🚨', name: '警灯', keywords: ['警灯', '警报', '危险'] },
      { emoji: '🚥', name: '红绿灯', keywords: ['红绿灯', '交通', '信号灯'] },
      { emoji: '🚦', name: '信号灯', keywords: ['信号灯', '交通', '红绿灯'] },
      { emoji: '🛑', name: '停止标志', keywords: ['停止', '标志', '交通'] },
      { emoji: '🚧', name: '施工', keywords: ['施工', '修路', '警告'] },
      { emoji: '⚓', name: '锚', keywords: ['锚', '船', '航海'] },
      { emoji: '🚢', name: '轮船', keywords: ['轮船', '船', '航海'] },
      { emoji: '⛵', name: '帆船', keywords: ['帆船', '航海', '航行'] },
      { emoji: '🛶', name: '独木舟', keywords: ['独木舟', '划船', '水上'] },
      { emoji: '🚤', name: '快艇', keywords: ['快艇', '船', '速度'] },
      { emoji: '🛳️', name: '客轮', keywords: ['客轮', '邮轮', '旅行'] },
      { emoji: '⛴️', name: '渡轮', keywords: ['渡轮', '船', '运输'] },
      { emoji: '🛥️', name: '游艇', keywords: ['游艇', '豪华', '船'] },
      { emoji: '✈️', name: '飞机', keywords: ['飞机', '航空', '旅行'] },
      { emoji: '🛩️', name: '小型飞机', keywords: ['飞机', '小型', '私人'] },
      { emoji: '🛫', name: '起飞', keywords: ['起飞', '飞机', '出发'] },
      { emoji: '🛬', name: '降落', keywords: ['降落', '飞机', '到达'] },
      { emoji: '🪂', name: '降落伞', keywords: ['降落伞', '跳伞', '滑翔'] },
      { emoji: '💺', name: '座位', keywords: ['座位', '椅子', '飞机'] },
      { emoji: '🚁', name: '直升机', keywords: ['直升机', '飞机', '航空'] },
      { emoji: '🚟', name: '索道', keywords: ['索道', '缆车', '山地'] },
      { emoji: '🚠', name: '缆车', keywords: ['缆车', '索道', '山地'] },
      { emoji: '🚡', name: '空中缆车', keywords: ['缆车', '索道', '观光'] },
      { emoji: '🛰️', name: '卫星', keywords: ['卫星', '太空', '科技'] },
      { emoji: '🚀', name: '火箭', keywords: ['火箭', '太空', '发射'] },
      { emoji: '🛸', name: 'UFO', keywords: ['飞碟', 'UFO', '外星人'] },
      { emoji: '🗺️', name: '世界地图', keywords: ['地图', '世界', '地理'] },
      { emoji: '🗾', name: '日本地图', keywords: ['地图', '日本', '地理'] },
      { emoji: '🧭', name: '指南针', keywords: ['指南针', '导航', '方向'] },
      { emoji: '🏔️', name: '雪山', keywords: ['雪山', '山', '高山'] },
      { emoji: '⛰️', name: '山', keywords: ['山', '山脉', '自然'] },
      { emoji: '🌋', name: '火山', keywords: ['火山', '熔岩', '爆发'] },
      { emoji: '🗻', name: '富士山', keywords: ['富士山', '日本', '山'] },
      { emoji: '🏕️', name: '露营', keywords: ['露营', '野营', '户外'] },
      { emoji: '⛺', name: '帐篷', keywords: ['帐篷', '露营', '野营'] },
      { emoji: '🏖️', name: '沙滩', keywords: ['沙滩', '海滩', '海边'] },
      { emoji: '🏜️', name: '沙漠', keywords: ['沙漠', '炎热', '干旱'] },
      { emoji: '🏝️', name: '小岛', keywords: ['小岛', '岛屿', '热带'] },
      { emoji: '🏞️', name: '国家公园', keywords: ['公园', '自然', '风景'] },
      { emoji: '🌅', name: '日出', keywords: ['日出', '早晨', '太阳'] },
      { emoji: '🌄', name: '日落', keywords: ['日落', '傍晚', '太阳'] },
      { emoji: '🌠', name: '流星', keywords: ['流星', '许愿', '星空'] },
      { emoji: '🎇', name: '烟花', keywords: ['烟花', '过年', '庆祝'] },
      { emoji: '🎆', name: '焰火', keywords: ['焰火', '烟花', '庆祝'] },
      { emoji: '🌌', name: '银河', keywords: ['银河', '星空', '宇宙'] },
      { emoji: '🌉', name: '桥', keywords: ['桥', '桥梁', '建筑'] },
      { emoji: '🏗️', name: '施工', keywords: ['施工', '建筑', '盖楼'] },
      { emoji: '🧱', name: '砖块', keywords: ['砖块', '砖头', '建筑'] },
      { emoji: '🏘️', name: '房屋', keywords: ['房屋', '房子', '住宅'] },
      { emoji: '🏚️', name: '废墟', keywords: ['废墟', '破旧', '房子'] },
      { emoji: '🏠', name: '房子', keywords: ['房子', '家', '住宅'] },
      { emoji: '🏡', name: '别墅', keywords: ['别墅', '房子', '家'] },
      { emoji: '🏢', name: '办公楼', keywords: ['办公楼', '写字楼', '办公'] },
      { emoji: '🏣', name: '日本邮局', keywords: ['邮局', '日本', '邮政'] },
      { emoji: '🏤', name: '邮局', keywords: ['邮局', '邮政', '寄信'] },
      { emoji: '🏥', name: '医院', keywords: ['医院', '医疗', '看病'] },
      { emoji: '🏦', name: '银行', keywords: ['银行', '金融', '钱'] },
      { emoji: '🏨', name: '酒店', keywords: ['酒店', '宾馆', '住宿'] },
      { emoji: '🏩', name: '情人酒店', keywords: ['酒店', '情人', '浪漫'] },
      { emoji: '🏪', name: '便利店', keywords: ['便利店', '商店', '24小时'] },
      { emoji: '🏫', name: '学校', keywords: ['学校', '上学', '学习'] },
      { emoji: '🏬', name: '商场', keywords: ['商场', '购物', '商店'] },
      { emoji: '🏭', name: '工厂', keywords: ['工厂', '工业', '生产'] },
      { emoji: '🏯', name: '城堡', keywords: ['城堡', '日本', '建筑'] },
      { emoji: '🏰', name: '欧式城堡', keywords: ['城堡', '欧式', '建筑'] },
      { emoji: '💒', name: '婚礼', keywords: ['婚礼', '结婚', '浪漫'] },
      { emoji: '🗼', name: '东京塔', keywords: ['东京塔', '日本', '地标'] },
      { emoji: '🗽', name: '自由女神', keywords: ['自由女神', '美国', '纽约'] },
      { emoji: '⛪', name: '教堂', keywords: ['教堂', '婚礼', '宗教'] },
      { emoji: '🕌', name: '清真寺', keywords: ['清真寺', '伊斯兰教', '宗教'] },
      { emoji: '🛕', name: '印度教寺庙', keywords: ['寺庙', '印度教', '宗教'] },
      { emoji: '🕍', name: '犹太教堂', keywords: ['教堂', '犹太教', '宗教'] },
      { emoji: '⛩️', name: '神社', keywords: ['神社', '日本', '宗教'] },
      { emoji: '🕋', name: '克尔白', keywords: ['麦加', '清真寺', '伊斯兰'] }
    ]
  },
  {
    id: 'flags',
    name: '🏳️ 旗帜',
    emojis: [
      { emoji: '🏳️', name: '白旗', keywords: ['白旗', '投降', '和平'] },
      { emoji: '🏴', name: '黑旗', keywords: ['黑旗', '旗帜', '海盗'] },
      { emoji: '🏁', name: '终点旗', keywords: ['终点旗', '比赛', '赛车'] },
      { emoji: '🚩', name: '三角旗', keywords: ['三角旗', '旗帜', '标记'] },
      { emoji: '🏳️‍🌈', name: '彩虹旗', keywords: ['彩虹旗', 'LGBT', '骄傲'] },
      { emoji: '🇨🇳', name: '中国国旗', keywords: ['中国', '国旗', '国家'] },
      { emoji: '🇺🇸', name: '美国国旗', keywords: ['美国', '国旗', '国家'] },
      { emoji: '🇯🇵', name: '日本国旗', keywords: ['日本', '国旗', '国家'] },
      { emoji: '🇰🇷', name: '韩国国旗', keywords: ['韩国', '国旗', '国家'] },
      { emoji: '🇬🇧', name: '英国国旗', keywords: ['英国', '国旗', '国家'] },
      { emoji: '🇫🇷', name: '法国国旗', keywords: ['法国', '国旗', '国家'] },
      { emoji: '🇩🇪', name: '德国国旗', keywords: ['德国', '国旗', '国家'] },
      { emoji: '🇮🇹', name: '意大利国旗', keywords: ['意大利', '国旗', '国家'] },
      { emoji: '🇪🇸', name: '西班牙国旗', keywords: ['西班牙', '国旗', '国家'] },
      { emoji: '🇷🇺', name: '俄罗斯国旗', keywords: ['俄罗斯', '国旗', '国家'] },
      { emoji: '🇦🇺', name: '澳大利亚国旗', keywords: ['澳大利亚', '国旗', '国家'] },
      { emoji: '🇨🇦', name: '加拿大国旗', keywords: ['加拿大', '国旗', '国家'] },
      { emoji: '🇧🇷', name: '巴西国旗', keywords: ['巴西', '国旗', '国家'] },
      { emoji: '🇮🇳', name: '印度国旗', keywords: ['印度', '国旗', '国家'] },
      { emoji: '🇸🇬', name: '新加坡国旗', keywords: ['新加坡', '国旗', '国家'] },
      { emoji: '🇹🇭', name: '泰国国旗', keywords: ['泰国', '国旗', '国家'] },
      { emoji: '🇻🇳', name: '越南国旗', keywords: ['越南', '国旗', '国家'] },
      { emoji: '🇲🇾', name: '马来西亚国旗', keywords: ['马来西亚', '国旗', '国家'] },
      { emoji: '🇵🇭', name: '菲律宾国旗', keywords: ['菲律宾', '国旗', '国家'] },
      { emoji: '🇮🇩', name: '印尼国旗', keywords: ['印尼', '印度尼西亚', '国旗'] },
      { emoji: '🇭🇰', name: '香港区旗', keywords: ['香港', '区旗', '中国'] },
      { emoji: '🇲🇴', name: '澳门区旗', keywords: ['澳门', '区旗', '中国'] },
      { emoji: '🇹🇼', name: '台湾旗帜', keywords: ['台湾', '旗帜', '中国'] },
      { emoji: '🇦🇷', name: '阿根廷国旗', keywords: ['阿根廷', '国旗', '足球'] },
      { emoji: '🇨🇱', name: '智利国旗', keywords: ['智利', '国旗', '国家'] },
      { emoji: '🇨🇴', name: '哥伦比亚国旗', keywords: ['哥伦比亚', '国旗', '国家'] },
      { emoji: '🇲🇽', name: '墨西哥国旗', keywords: ['墨西哥', '国旗', '国家'] },
      { emoji: '🇵🇹', name: '葡萄牙国旗', keywords: ['葡萄牙', '国旗', '国家'] },
      { emoji: '🇬🇷', name: '希腊国旗', keywords: ['希腊', '国旗', '国家'] },
      { emoji: '🇳🇱', name: '荷兰国旗', keywords: ['荷兰', '国旗', '国家'] },
      { emoji: '🇧🇪', name: '比利时国旗', keywords: ['比利时', '国旗', '国家'] },
      { emoji: '🇨🇭', name: '瑞士国旗', keywords: ['瑞士', '国旗', '国家'] },
      { emoji: '🇦🇹', name: '奥地利国旗', keywords: ['奥地利', '国旗', '国家'] },
      { emoji: '🇸🇪', name: '瑞典国旗', keywords: ['瑞典', '国旗', '国家'] },
      { emoji: '🇳🇴', name: '挪威国旗', keywords: ['挪威', '国旗', '国家'] },
      { emoji: '🇩🇰', name: '丹麦国旗', keywords: ['丹麦', '国旗', '国家'] },
      { emoji: '🇫🇮', name: '芬兰国旗', keywords: ['芬兰', '国旗', '国家'] },
      { emoji: '🇵🇱', name: '波兰国旗', keywords: ['波兰', '国旗', '国家'] },
      { emoji: '🇨🇿', name: '捷克国旗', keywords: ['捷克', '国旗', '国家'] },
      { emoji: '🇭🇺', name: '匈牙利国旗', keywords: ['匈牙利', '国旗', '国家'] },
      { emoji: '🇹🇷', name: '土耳其国旗', keywords: ['土耳其', '国旗', '国家'] },
      { emoji: '🇮🇱', name: '以色列国旗', keywords: ['以色列', '国旗', '国家'] },
      { emoji: '🇸🇦', name: '沙特国旗', keywords: ['沙特', '阿拉伯', '国旗'] },
      { emoji: '🇦🇪', name: '阿联酋国旗', keywords: ['阿联酋', '迪拜', '国旗'] },
      { emoji: '🇪🇬', name: '埃及国旗', keywords: ['埃及', '国旗', '非洲'] },
      { emoji: '🇿🇦', name: '南非国旗', keywords: ['南非', '国旗', '非洲'] },
      { emoji: '🇳🇬', name: '尼日利亚国旗', keywords: ['尼日利亚', '国旗', '非洲'] },
      { emoji: '🇰🇪', name: '肯尼亚国旗', keywords: ['肯尼亚', '国旗', '非洲'] },
      { emoji: '🇳🇿', name: '新西兰国旗', keywords: ['新西兰', '国旗', '大洋洲'] },
      { emoji: '🇮🇪', name: '爱尔兰国旗', keywords: ['爱尔兰', '国旗', '国家'] },
      { emoji: '🇸🇨', name: '苏格兰国旗', keywords: ['苏格兰', '国旗', '英国'] }
    ]
  }
];
